name: 'Cypress E2E Testing'

trigger:
- master

stages:
- stage: e2e_testing_stage_chrome
  displayName: 'Chrome E2E Testing'
  jobs:
  - job: e2e_testing_job_chrome
    displayName: 'Run E2E in Chrome'
    pool:
      vmImage: windows-2019
    steps:
      - template: templates/browserRun.yml
        parameters:
          browserType: chrome
          verbose: true

- stage: e2e_testing_stage_firefox
  displayName: 'Firefox E2E Testing'
  dependsOn: []
  jobs:
  - job: e2e_testing_job_firefox
    displayName: 'Run E2E in Firefox'
    pool:
      vmImage: macos-latest
    steps:
      - template: templates/browserRun.yml
        parameters:
          browserType: firefox
          verbose: true
          
- stage: e2e_testing_stage_edge
  displayName: 'Edge E2E Testing'
  dependsOn: []
  jobs:  
  - job: e2e_testing_job_edge
    displayName: 'Run E2E in Edge'
    pool:
      vmImage: macos-latest
    steps:
      - template: templates/browserRun.yml
        parameters:
          browserType: edge
          verbose: true
